# Generated by Django 6.0.1 on 2026-01-20 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
